### ISSUE TITLE
Bug: Division by Zero Does Not Raise Error in Calculator Code

### ISSUE THREAD

**Issue by geekyharsh05** [ShubhamPatel81/python_code#1]
### Steps to Reproduce:

1. Run the calculator code.
2. Select the division operation.
3. Enter a non-zero first number.
4. Enter zero as the second number.
5. Observe the absence of an error or warning message.

### Suggested Solution:

Modify the code to include a check for division by zero and raise a `ZeroDivisionError` with an informative message. Implement proper exception handling in the main code to handle the error and provide meaningful feedback to the user.

### `If this issue is unassigned, kindly assign it to me`, and I'll be glad to work on resolving it.

**Comment by ShubhamPatel81** [comment]
commited
